version: '3.8'
services:
  teiid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-federation-teiid
    ports:
      - '0.0.0.0:31000:31000'
      - '0.0.0.0:18080:8080'
      - '0.0.0.0:19990:9990'
      - '0.0.0.0:35432:35432'
    networks:
      - ascam-networks
    volumes:
      - teiid-standalone-configuration:/opt/jboss/wildfly/standalone/configuration
      - teiid-domain-configuration:/opt/jboss/wildfly/domain/configuration

networks:
  ascam-networks:
    external: True

volumes:
  teiid-standalone-configuration: { }
  teiid-domain-configuration: { }